---
title: R = r + R-Studio
author: Florencia
date: '2019-05-01'
slug: hola-mundo-2-6.es-es
categories:
  - Hola Mundo
tags:
  - AprendiendoR
  - doctorado
  - RStudio
keywords:
  - tech
thumbnailImage: 
   https://res.cloudinary.com/flor/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1557182739/4_bpjexb.png
thumbnailImagePosition: right
coverimage:
   https://res.cloudinary.com/flor/image/upload/v1557153493/2_pft8xl.png
summary: " Obstáculos que encontré al aprender a programar en R (y cómo superarlos)"
---

## ¿Cómo llegue ahí?
En el verano de 2015 tomé un curso de postgrado, donde en una práctica nos enseñaban a realizar una simulación sencilla con R. Para este trabajo práctico instalé R en mi PC y comencé a reproducir las líneas de código a medida que las iba explicando el docente. En un momento de duda consulto al asistente de clase. Al mirar mi pantalla, me dice: “recomiendo fuertemente que instales también R-Studio, es mucho más fácil”.

## Reflexiones 
 Si bien el curso no era sobre R, me fuí con tres ideas sin las cuales no hubiese podido empezar este camino:

1)  La noción de que R y RStudio eran cosas diferentes: R-Studio permitía una gestión del código más sencilla. 
Haciendo una analogía podríamos comparar [R con el motor de un auto y R-Studio con el tablero de un auto](https://moderndive.com/2-getting-started.html), que facilita al usuario hacerlo funcionar. Me pareció una buena forma de entender la diferencia entre ambos.

2)  R y R-Studio instalados en la PC,

y, lo que no es menor,

3)  Haber corrido código y darme cuenta que *era algo que yo también podía hacer*.

Pero no me malinterpreten. Tranquilamente podría haber resuelto la práctica de ese curso usando solo la consola de R. Lo que no me hubiese sido tan sencillo es continuar aprendiendo por mi cuenta sin haber usado la IDE de RStudio.

## Recomendaciones 
* Primero debes instalar gratis [R](https://www.r-project.org/) y luego [R-Studio](https://www.rstudio.com/products/rstudio/download/). 

* A veces es bueno saber que existen formas de emplear R-Studio desde la web sin instalar como [R-Studio Cloud](https://rstudio.cloud/)

* En grupos de usuarios suelen hacerse jornadas de instalación donde ofrecen ayuda con los pasos necesarios para tener funcionando R y R-Studio en tu compu. 

* También hay tutoriales muy útiles como [este](https://github.com/rivaquiroga/RLadies-Santiago/blob/master/2018-04_taller_primeros_pasos_en_R.Rmd).

* Para comenzar se puede seleccionar desde la web un breve tutorial para principiantes de algo con lo que te sientas más cómodo y trates de reproducirlo. Eso te ayudará con la sensación de que no eres capaz de hacerlo.

### Bibliografía

Ismay C, Kim A. (2019) Chapter 2: Getting Started with Data in R. En: [Moderndive. Statistical Inference via Data Science](https://moderndive.com/). A moderndive into R and the tidyverse.

