---
title: Where to publish your ShinyApp?
author: Florencia
date: '2020-03-04'
slug: where-to-publish-your-ShinyApp.en-us
categories:
  - Shiny
tags:
  - ShinyApp
  - publish
  - journal
  - code
  - software
  - open source
  - science
keywords:
  - rstats
thumbnailImage: 
  https://res.cloudinary.com/flor/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1582548588/2_k0l388.png
thumbnailImagePosition: left
coverimage:
  https://res.cloudinary.com/flor/image/upload/v1582548588/2_k0l388.png
summary: "My experience publishing a ShinyApp - Links to lists of Scientific Journals accepting ShinyApps"
---

## Motivation
I started to develop ShinyApps because of my research. The development of a ShinyApp for the analysis of toxicological databases allowed me to explore the data in relation to different criteria.

## Where to publish?

After finishing the app, my first question was whether to publish the ShinyApp. Should I include it as supplementary material of other paper or could be published as software itself?

I got valuable suggestions in the RStudio Community forum including a list of possible journals accepting ShinyApps, in the following [thread](https://community.rstudio.com/t/can-i-publish-a-shiny-app-in-a-scientific-journal-how-where/6306). I found also a lot of resources in this post: [In which journals should I publish my software? By Neil Chue Hong](https://www.software.ac.uk/which-journals-should-i-publish-my-software). Finally, I decided to try with [The Journal of Open Source Software](https://joss.theoj.org/). 

One advantage of publishing the code itself is that the journal' review process focused on how to release the code as open source software, a concept that as researchers we are barely familiarized. 

As an example, I included a file to indicate how users could contribute to my ShinyApp and a license. I probably would not have done any of these steps of trying to publish the ShinyApp as supplementary material of a paper.

## My first "shiny" paper

Last year I published a first ShinyApp to analyze ecotoxicological databases.

D’Andrea et al., (2019). [shinyssd v1.0: Species Sensitivity Distributions for Ecotoxicological Risk Assessment](https://joss.theoj.org/papers/10.21105/joss.00785). Journal of Open Source Software,
4(37), 785

## Is the Scientific Paper outdated? 

I have recently read a very interesting article called [The Scientific Paper Is Outdated. By R. Abernathey](https://www.chronicle.com/article/The-Scientific-Paper-Is/248045). 

> Should scientists spend more time developing software? What do you think?

### Thanks!
I want to thank [Maelle Salmon](https://masalmon.eu/), who encouraged me to publish this post