---
title: Tutoriales en R
author: Florencia
date: '2020-02-20'
slug: tutoriales-en-R.es-es
categories:
  - Tutoriales
tags:
  - tutoriales
  - rstates
  - gratis
  - educación
keywords:
  - tutoriales
thumbnailImage: 
  https://res.cloudinary.com/flor/image/upload/e_auto_brightness,o_70/v1580575702/matry_rep2gq.jpg
thumbnailImagePosition: right
coverimage:
   https://res.cloudinary.com/flor/image/upload/v1580574062/matryoshka_dolls-wallpaper-1366x768_zntpia.jpg
summary: "Tips para realizar tu tutorial de R con el framework gratuito de Ines Montani"
---

# Tutoriales

Existen dos formas de realizar tutoriales en R, con el [framework gratuito]() que creo [Ines Montani]() y/o el paquete [learnR]().

El [post]() en el que recientemente colaboré junto a [Ted Laderas](), quien desarrollo el paquete [decampr]() y Jessica X para el blog de RStudio Education comenta algunas diferencias entre ambas formas de realizar tutoriales.

Puedes encontrar una lista de todos los tutoriales realizados con este framework [aquí]().

En este post voy a generar una guía rápida sobre como realizar desde 0 un tutorial con el framework de Ines Montani. 
¿Sos un profresor de estadística y querés dejar tu tutorial de online? Cómo mencioné este framework no se usa desde R por lo qur puede presentar ciertas dificultades para alguien no familiarizado.

Warning! Un tutorial no es lo mismo que un curso, podés leer más sobre esto [aquí]().

## Receta para tu tutorial con el framework de Ines Montani

Lo primero que debo decir sobre el tutorial de Ines, es que la [documentación]() es excelente. Siempre que tuve algún tipo de duda al respecto, encontré una posible solución leyendolo.


## Paso 1: Los ingredientes.

Estos cursos poseen: (1) filminas con texto, (2) ejercicios de opción múltiple y (3) ejercios de completar parte de código faltante. 

El tutorial se divide en capítulos. Cada uno de estos tres "bloques" en distinta combinación puede constituir un capítulo.

Lo que deberías realizar es adaptar tu material antes de seguir avanzando con el tutorial o generarlo directamente considerando este formato.

## Paso 2: Preparación.

Cada uno de los 3 formatos que mencioné antes tiene su tipo de escritura particular y se guardan en un lugar particular dentro de la estructura de archivos, qué es mas o menos la siguiente:





## Paso 3: La cocción.

Para que el curso funcioné se realiza una coccion desde la branch de github desde la página de "Mybinder.org". Esto permite generar una máquina virtual que permite que corra el código que cargamos en el curso.

Este pasó, como toda cocción, puede demorar algún tiempo.


## Paso 4: Decoración

Los cambios más significativos constan de 
(1) agregar un logo y 
(2) modificar los colores de los botones.

#### ¿cómo cambio el tamaño del logo?


#### ¿Cómo agregar un favicon?

Si no sabes que colores elegir existen páginas web que te permiten seleccionar paletas de colores.

Aquí vas a poder encontrar la parte de la documentación de Ines dónde se deja el curso disponible

### Sobre el paquete learnR

En el caso de learnR cuenta con la ventaja de que es un paquete de R y la forma de ser usada es quizás más intuitiva. Aquí dejo material relevante que puede ser consultado sobre su uso.

Hablaré más sobre learnR en próximos posteos.

Quiero agradecer a Erin LeDell, Yanina Bellini Saibene y Roxana Villafañe








